site_name: My Documentation
site_description: Our documentation site to get 20/20 :).

# Configuration
theme:
  name: material

# Navigation structure
nav:
  - Documentation:
      - Setup Guide: README.md
      - Test Results: results.html
site_dir: site
docs_dir: docs
