site_name: My Documentation
site_description: A description of your documentation site.

# Theme configuration
theme:
  name: material

# Navigation structure
nav:
  - Documentation:
      - Setup Guide: SETUP.md
      - Test Results: RESULTS.html

docs_dir: docs
