site_name: My Documentation
site_description: Our documentation site to get 20/20 :).

# Configuration
site_dir: site
theme:
  name: material

# Navigation structure
nav:
  - Documentation:
      - Setup Guide: SETUP.md
      - Test Results: RESULTS.html

docs_dir: docs
