site_name: My Documentation
site_description: A description of your documentation site.

# Theme configuration
theme:
  name: material

# Navigation structure
nav:
  - Home: index.md
  - About: about.md
  - Documentation:
      - Introduction: introduction.md
      - Setup Guide: setup.md
      - Test Results: results.html

docs_dir: docs
