name: Rapports Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with pytest
        run: |
          pytest --junitxml=reports/test_report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
            name: junit-test-report
            path: reports/test_report.xml
