name: Rapports Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with pytest and generate HTML report
        run: |
          # Installe pytest-html pour générer un rapport HTML
          pip install pytest-html
          pytest --html=reports/test_report.html

      - name: Commit and push the HTML report to main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git stash || echo "No local changes to stash"
          git fetch --all
          git checkout main

          cp reports/test_report.html docs/test_report.html
          
          git add docs/test_report.html
          git commit -m "Ajout du rapport de test HTML"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
