name: Rapports Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Tests
        run: pytest --html=reports/test_report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
            name: test-report
            path: reports/test_report.html

